// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR-JNXjPZAsn-oAJezfxELhRWXfdNbTy8',
    appId: '1:184702438747:web:23e9d3d425c37e97e19e7e',
    messagingSenderId: '184702438747',
    projectId: 'vidyurakshak-sih',
    authDomain: 'vidyurakshak-sih.firebaseapp.com',
    storageBucket: 'vidyurakshak-sih.appspot.com',
    measurementId: 'G-DSR8ZYK8E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC25laAHCfHnz9kQsdYLbkXMtNWfNh1jvY',
    appId: '1:184702438747:android:25d5bf11ccfe7b8de19e7e',
    messagingSenderId: '184702438747',
    projectId: 'vidyurakshak-sih',
    storageBucket: 'vidyurakshak-sih.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGhfI-Lu--YoQ-6P7P-rG7ZWb7cworfuY',
    appId: '1:184702438747:ios:7c6eaa8131f8b34ce19e7e',
    messagingSenderId: '184702438747',
    projectId: 'vidyurakshak-sih',
    storageBucket: 'vidyurakshak-sih.appspot.com',
    iosBundleId: 'com.example.vidurakshakSih',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGhfI-Lu--YoQ-6P7P-rG7ZWb7cworfuY',
    appId: '1:184702438747:ios:00da4a182582ad9ee19e7e',
    messagingSenderId: '184702438747',
    projectId: 'vidyurakshak-sih',
    storageBucket: 'vidyurakshak-sih.appspot.com',
    iosBundleId: 'com.example.vidurakshakSih.RunnerTests',
  );
}
